name: lucyinthesky_rates
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
  
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  intl: ^0.18.1
  shared_preferences: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  
flutter:
  uses-material-design: true

assets:
  - .env
